### ISSUE TITLE
volumes don't seem to work the docker way

### ISSUE THREAD

**Issue by danfromtitan** [portertech/kitchen-docker#124]
Looks like I don't have much luck with making volumes work in kitchen-docker.
Added a volume and container inspect shows:

```
    "Volumes": {
        "/var/lib/activemq": "/var/lib/docker/vfs/dir/20fb19056...."
    },
    "VolumesRW": {
        "/var/lib/activemq": true
```

I was expecting gem would create a local directory on docker host and attach that to the container, such as in:

```
    "Volumes": {
        "/var/lib/activemq": "/var/lib/activemq"
```

I wonder whether u could shed some light on how kitchen-docker gem deals with volumes.

Driver config below:

```
platforms:
  - name: ubuntu-12.04
    driver_config:
      platform: ubuntu
      require_chef_omnibus: false
      socket: tcp://my.docker.host:5000
      image: myorg/activemq:5.11.1
      use_cache: false
      use_sudo: false
      hostname: amq.my.docker.host
      instance_name: amq
      volume: /var/lib/activemq
```
