### ISSUE TITLE
Question: provision_command scope

### ISSUE THREAD

**Issue by walterdolce** [portertech/kitchen-docker#145]
Hi there,

This is just a question really as I didn't seem to see it in the README. 
What is the scope for `provision_command`?

I currently have this bits in my `.kitchen.yml` which is working :ok_hand: :
```
 ...
platforms:
  - name: centos-6.6
    driver_config:
      provision_command:
        - groupadd vagrant
        - useradd -g vagrant vagrant
 ...
```

When I tried the following, though, it didn't work:
```
   ...
suites:
  - name: my_suite_name
    driver_config:
      provision_command:
        - groupadd vagrant
        - useradd -g vagrant vagrant
    run_list:
      - recipe[my_cookbook::my_recipe]
    attributes:
   ...
```

So the question, does the `provision_command` only work on a `platform` basis?

Thanks!
