### ISSUE TITLE
Serverspec's port should_be_listening does not work with kitchen-docker

### ISSUE THREAD

**Issue by metmajer** [portertech/kitchen-docker#150]
Hi - thank you for providing this great project!

I have tried to migrate our Vagrant-based testing to a Docker-based approach to save ourselves some minutes on each instance. Unfortunately, when it comes to asserting the availability of a port in Serverspec via:

```
describe port(9998) do
  it { should be_listening }
end
```

this leads to the following result:

```
Port "9998"
 should be listening (FAILED - 1)

Failures:
 1) Port "9998" should be listening
    Failure/Error: it { should be_listening }
      expected Port "9998" to be listening
```

Here is an excerpt of my .kitchen.yml:

```
---
provisioner:
  name: chef_zero

driver:
  name: docker

platforms:
  - name: debian-7.4
    run_list:
      - recipe[apt]
      - recipe[java]
    attributes:
      java:
        jdk_version: 7

suites:
  - name: collector
    run_list:
      - recipe[dynatrace::collector]
```

The availability of the port is successfully asserted when using the kitchen-vagrant driver. I have also figured out that the port can be accessed from inside the Docker container via a simple `telnet localhost 9998`.

Thanks!
