### ISSUE TITLE
Failed to complete #create action: [undefined method `create' for Tempfile:Class]

### ISSUE THREAD

**Issue by dj-wasabi** [portertech/kitchen-docker#159]
Hi,

I don't know what I'm doing wrong. I have installed the gems via bundle via rvm (Test it with ruby 1.9.3 and 2.0.0):
```
gem 'test-kitchen', '>= 1.4.0'
gem 'kitchen-docker', '>= 2.3.0'
gem 'kitchen-ansible'
```

When I run kitchen test, I get the following messag:
```
-bash-4.2$ kitchen test
-----> Starting Kitchen (v1.4.2)
-----> Cleaning up any prior instances of <zabbix-20-mysql-centos-66>
-----> Destroying <zabbix-20-mysql-centos-66>...
       Finished destroying <zabbix-20-mysql-centos-66> (0m0.00s).
-----> Testing <zabbix-20-mysql-centos-66>
-----> Creating <zabbix-20-mysql-centos-66>...
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #create action: [undefined method `create' for Tempfile:Class]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

Docker is running:
```
-bash-4.2$ systemctl status docker.service
docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled)
   Active: active (running) since Mon 2015-08-17 16:24:59 CEST; 20min ago
     Docs: https://docs.docker.com
 Main PID: 8443 (docker)
   CGroup: /system.slice/docker.service
           └─8443 /usr/bin/docker -d -H fd://
```

When I execute the 'kitchen diagnose --all' I don't see any problems. (I can show the output, but it is very long)

This is my .kitchen.yml:
```
---
driver:
  name: docker
  provision_command: sed -i '/tsflags=nodocs/d' /etc/yum.conf

provisioner:
  name: ansible_playbook
  ansible_yum_repo: "http://mirror.logol.ru/epel/6/x86_64/epel-release-6-8.noarch.rpm"
  hosts: localhost
  requirements_path: requirements.yml
  require_ruby_for_busser: false

platforms:
  - name: centos-6.6
    provisioner:
      playbook: playbooks/rh6.yml
      ansible_diff: true

suites:
  - name: zabbix-20-mysql
    attributes:
      extra_vars:
        zabbix_version: 2.0
        database_type: mysql
        database_type_long: mysql
```

All is running on Oracle Enterprise LInux 7.1, 64 Bit as user Jenkins (As it an goal to run it via Jenkins).
When I run it locally on my mac, everything works fine.
