### ISSUE TITLE
Waiting for SSH service on 192.168.99.100:32777, retrying in 3 seconds - loop

### ISSUE THREAD

**Issue by ashleyconnor** [portertech/kitchen-docker#202]
I had this all working at some point but something appears to have come loose in a recent version of docker.

```
D      [kitchen::driver::docker command] BEGIN (docker -H tcp://192.168.99.100:2376 port 183ddb4bcf7c267e8ad91dd13f696b2f0af5d1f9e91756272e4dee00cb77e460 22/tcp)
       0.0.0.0:32777
D      [kitchen::driver::docker command] END (0m0.03s)
D      [SSH] opening connection to kitchen@192.168.99.100<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :port=>32777, :compression=>true, :compression_level=>6, :keepalive=>true, :keepalive_interval=>60, :timeout=>15, :password=>"kitchen"}>
D      [SSH] connection failed (#<Net::SSH::Disconnect: disconnected: Too many authentication failures for kitchen (2)>)
       Waiting for SSH service on 192.168.99.100:32777, retrying in 3 seconds
D      [SSH] opening connection to kitchen@192.168.99.100<{:user_known_hosts_file=>"/dev/null", :paranoid=>false, :port=>32777, :compression=>true, :compression_level=>6, :keepalive=>true, :keepalive_interval=>60, :timeout=>15, :password=>"kitchen", :user=>"kitchen"}>
D      [SSH] connection failed (#<Net::SSH::Disconnect: disconnected: Too many authentication failures for kitchen (2)>)
       Waiting for SSH service on 192.168.99.100:32777, retrying in 3 seconds
```

---

Gemfile
```
source "https://rubygems.org"

gem 'test-kitchen'
gem 'kitchen-docker'
gem 'kitchen-ansible'
gem 'serverspec'
```

.kitchen.yml
```
---
driver:
    name: docker
    use_sudo: false

provisioner:
    hosts: test-kitchen
    name: ansible_playbook
    roles_path: roles
    ansible_verbosity: 2
    ansible_verbose: true

platforms:
    - name: centos
      driver_config:
          image: stackio/ansible-centos6
          platform: centos
suites:
    - name: default
```

* `docker --version` - Docker version 1.11.0, build 4dc5990
* `kitchen --version` - Test Kitchen version 1.7.3

If I run `docker ps` after running `kitchen create` I get:

```
→ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                   NAMES
538dca6851ab        994f402e05d6        "/usr/sbin/sshd -D -o"   7 minutes ago       Up 7 minutes        0.0.0.0:32777->22/tcp   goofy_dubinsky
```
